// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function GetAppVersion():Promise<string>;

export function GetDiagnosticUpdateSchema():Promise<core.DiagnosticUpdate>;

export function RunDiagnosticsStream():Promise<void>;

export function SaveToFile(arg1:string):Promise<void>;

export function SetVersion(arg1:string):Promise<void>;
