// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['core']['App']['GetAppVersion']();
}

export function GetDiagnosticUpdateSchema() {
  return window['go']['core']['App']['GetDiagnosticUpdateSchema']();
}

export function RunDiagnosticsStream() {
  return window['go']['core']['App']['RunDiagnosticsStream']();
}

export function SaveToFile(arg1) {
  return window['go']['core']['App']['SaveToFile'](arg1);
}

export function SetVersion(arg1) {
  return window['go']['core']['App']['SetVersion'](arg1);
}
